[package]
name = "pew"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
floating_origin = { path = "../floating_origin" }
bevy-inspector-egui = "0.13"
bytemuck = "1"
rand = "0.8"
